version: "3.8"

services:
  api-gateway:
    container_name: api-gateway
    build: ./api-gateway
    volumes:
      - ./api-gateway/src:/usr/app/src
    ports:
      - "7000:7000"
    networks:
      - trab-network

  chat-app:
    container_name: chat-app
    build: ./chat-app
    volumes:
      - ./chat-app/src:/usr/app/src
    ports:
      - "7001:7001"
    env_file:
      - ./chat-app/.env
    depends_on:
      - api-gateway
    networks:
      - trab-network

  chat-service:
    container_name: chat-service
    build: ./chat-service
    volumes:
      - ./chat-service/src:/usr/app/src
    ports:
      - "7100:7100"
    depends_on:
      - chat-service-db
    networks:
      - trab-network

  chat-service-db:
    image: mysql:5.7.20
    ports:
      - "7200:3360"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db
    networks:
      - trab-network

  users-service:
    build: ./users-service
    volumes:
      - ./users-service/src:/usr/app/src
    ports:
      - "7101:7101"
    depends_on:
      - users-service-db
    networks:
      - trab-network

  users-service-db:
    image: mysql:5.7.20
    ports:
      - "7201:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db
    networks:
      - trab-network

  phpmyadmin:
    image: phpmyadmin
    volumes:
      - ./phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
    links:
      - "users-service-db:users-service-db"
      - "chat-service-db:chat-service-db"
    ports:
      - "7300:80"
    depends_on:
      - chat-service-db
      - users-service-db
    networks:
      - trab-network

networks: 
  trab-network:
      driver: bridge